spring.application.name=APIGateway
server.port=9191

#Add Routing
spring.cloud.gateway.server.webflux.routes[0].id=CUSTOMER
spring.cloud.gateway.server.webflux.routes[0].uri=lb://CUSTOMER
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/v1/customer/**
 
spring.cloud.gateway.server.webflux.routes[1].id=BANKACCOUNT
spring.cloud.gateway.server.webflux.routes[1].uri=lb://BANKACCOUNT
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/v1/bank/**

spring.cloud.gateway.server.webflux.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.name=BANKACCOUNT
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.fallbackUri=forward:/bankFallback

spring.cloud.gateway.server.webflux.routes[2].id=AUTH_MICROSERVICE
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8090/
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/auth/**


management.endpoints.web.exposure.include=*
 
 
#Circuit Breaker
resilience4j.circuitbreaker.instances.BANKACCOUNT.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.BANKACCOUNT.slidingWindowSize=6
resilience4j.circuitbreaker.instances.BANKACCOUNT.failureRateThreshold=50
resilience4j.circuitbreaker.instances.BANKACCOUNT.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.BANKACCOUNT.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.BANKACCOUNT.minimumNumberOfCalls=5




